#!/bin/bash
# Config for when running from the source directory.

basedir=$(cd -L "$(dirname "$0")" >/dev/null 2>&1 && pwd -L)

echo 'myports_bin_dir="'"${basedir}"'"'
echo 'myports_template_dir="'"${basedir}"'"'
